spring.application.name=lead-system

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/lead_system}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
